# Spring Boot configuration
spring:
  profiles:
    active: sumit
# Spring Security configuration
security:
  oauth2:
    client:
      clientId: 183898088179-hm4h7gcr7e52of6ol5mivi2g4a1m48vf.apps.googleusercontent.com
      clientSecret: nfcrpZIal4pNi_rf6gzPJYhq
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: email
      #scope: https://www.googleapis.com/auth/games
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
# Server configuration
server:
 port: 8080
 
logging:
  level:
    org.springframework.web: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: C:/application.log